// Dati SRD 5.1 — mostri e oggetti magici (5e-bits/5e-database, licenza OGL/CC-BY-4.0).
// Estratti dal generatore originale: una voce per riga, per diff leggibili.
import type { Monster, MagicItem, Rarity } from "./engine";

export const MONSTERS: Monster[] = [
  {"name":"Awakened Shrub","cr":0,"xp":10,"type":"plant","size":"Small","ac":9,"hp":10,"hpDice":"3d6","speed":20,"tags":["plant","plant_theme"]},
  {"name":"Baboon","cr":0,"xp":10,"type":"beast","size":"Small","ac":12,"hp":3,"hpDice":"1d6","speed":30,"tags":["beast"]},
  {"name":"Badger","cr":0,"xp":10,"type":"beast","size":"Tiny","ac":10,"hp":3,"hpDice":"1d4+1","speed":20,"tags":["beast"]},
  {"name":"Bat","cr":0,"xp":10,"type":"beast","size":"Tiny","ac":12,"hp":1,"hpDice":"1d4-1","speed":5,"tags":["beast","wild_beast"]},
  {"name":"Cat","cr":0,"xp":10,"type":"beast","size":"Tiny","ac":12,"hp":2,"hpDice":"1d4","speed":40,"tags":["beast","wild_beast"]},
  {"name":"Commoner","cr":0,"xp":10,"type":"humanoid","size":"Medium","ac":10,"hp":4,"hpDice":"1d8","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Crab","cr":0,"xp":10,"type":"beast","size":"Tiny","ac":11,"hp":2,"hpDice":"1d4","speed":20,"tags":["beast"]},
  {"name":"Deer","cr":0,"xp":10,"type":"beast","size":"Medium","ac":13,"hp":4,"hpDice":"1d8","speed":50,"tags":["beast","wild_beast"]},
  {"name":"Eagle","cr":0,"xp":10,"type":"beast","size":"Small","ac":12,"hp":3,"hpDice":"1d6","speed":10,"tags":["beast","wild_beast"]},
  {"name":"Frog","cr":0,"xp":0,"type":"beast","size":"Tiny","ac":11,"hp":1,"hpDice":"1d4-1","speed":20,"tags":["beast","wild_beast"]},
  {"name":"Giant Fire Beetle","cr":0,"xp":10,"type":"beast","size":"Small","ac":13,"hp":4,"hpDice":"1d6+1","speed":30,"tags":["beast","fire","giantkin","vermin"]},
  {"name":"Goat","cr":0,"xp":10,"type":"beast","size":"Medium","ac":10,"hp":4,"hpDice":"1d8","speed":40,"tags":["beast","wild_beast"]},
  {"name":"Hawk","cr":0,"xp":10,"type":"beast","size":"Tiny","ac":13,"hp":1,"hpDice":"1d4-1","speed":10,"tags":["beast","wild_beast"]},
  {"name":"Homunculus","cr":0,"xp":10,"type":"construct","size":"Tiny","ac":13,"hp":5,"hpDice":"2d4","speed":20,"tags":["construct","construct_theme"]},
  {"name":"Hyena","cr":0,"xp":10,"type":"beast","size":"Medium","ac":11,"hp":5,"hpDice":"1d8+1","speed":50,"tags":["beast","wild_beast"]},
  {"name":"Jackal","cr":0,"xp":10,"type":"beast","size":"Small","ac":12,"hp":3,"hpDice":"1d6","speed":40,"tags":["beast","wild_beast"]},
  {"name":"Lemure","cr":0,"xp":10,"type":"fiend","size":"Medium","ac":7,"hp":13,"hpDice":"3d8","speed":15,"tags":["devil","fiend"]},
  {"name":"Lizard","cr":0,"xp":10,"type":"beast","size":"Tiny","ac":10,"hp":2,"hpDice":"1d4","speed":20,"tags":["beast","wild_beast"]},
  {"name":"Octopus","cr":0,"xp":10,"type":"beast","size":"Small","ac":12,"hp":3,"hpDice":"1d6","speed":5,"tags":["beast","wild_beast"]},
  {"name":"Owl","cr":0,"xp":10,"type":"beast","size":"Tiny","ac":11,"hp":1,"hpDice":"1d4-1","speed":5,"tags":["beast","wild_beast"]},
  {"name":"Quipper","cr":0,"xp":10,"type":"beast","size":"Tiny","ac":13,"hp":1,"hpDice":"1d4-1","speed":40,"tags":["beast"]},
  {"name":"Rat","cr":0,"xp":10,"type":"beast","size":"Tiny","ac":10,"hp":1,"hpDice":"1d4-1","speed":20,"tags":["beast","wild_beast"]},
  {"name":"Raven","cr":0,"xp":10,"type":"beast","size":"Tiny","ac":12,"hp":1,"hpDice":"1d4-1","speed":10,"tags":["beast"]},
  {"name":"Scorpion","cr":0,"xp":10,"type":"beast","size":"Tiny","ac":11,"hp":1,"hpDice":"1d4-1","speed":10,"tags":["beast","vermin"]},
  {"name":"Sea Horse","cr":0,"xp":0,"type":"beast","size":"Tiny","ac":11,"hp":1,"hpDice":"1d4-1","speed":20,"tags":["aquatic","beast","wild_beast"]},
  {"name":"Shrieker","cr":0,"xp":10,"type":"plant","size":"Medium","ac":5,"hp":13,"hpDice":"3d8","speed":0,"tags":["plant","plant_theme"]},
  {"name":"Spider","cr":0,"xp":10,"type":"beast","size":"Tiny","ac":12,"hp":1,"hpDice":"1d4-1","speed":20,"tags":["beast","vermin"]},
  {"name":"Vulture","cr":0,"xp":10,"type":"beast","size":"Medium","ac":10,"hp":5,"hpDice":"1d8+1","speed":10,"tags":["beast"]},
  {"name":"Weasel","cr":0,"xp":10,"type":"beast","size":"Tiny","ac":13,"hp":1,"hpDice":"1d4-1","speed":30,"tags":["beast"]},
  {"name":"Bandit","cr":0.125,"xp":25,"type":"humanoid","size":"Medium","ac":12,"hp":11,"hpDice":"2d8+2","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Blood Hawk","cr":0.125,"xp":25,"type":"beast","size":"Small","ac":12,"hp":7,"hpDice":"2d6","speed":10,"tags":["beast","wild_beast"]},
  {"name":"Camel","cr":0.125,"xp":25,"type":"beast","size":"Large","ac":9,"hp":15,"hpDice":"2d10+4","speed":50,"tags":["beast"]},
  {"name":"Cultist","cr":0.125,"xp":25,"type":"humanoid","size":"Medium","ac":12,"hp":9,"hpDice":"2d8","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Flying Snake","cr":0.125,"xp":25,"type":"beast","size":"Tiny","ac":14,"hp":5,"hpDice":"2d4","speed":30,"tags":["beast","wild_beast"]},
  {"name":"Giant Crab","cr":0.125,"xp":25,"type":"beast","size":"Medium","ac":15,"hp":13,"hpDice":"3d8","speed":30,"tags":["beast","giantkin","vermin"]},
  {"name":"Giant Rat","cr":0.125,"xp":25,"type":"beast","size":"Small","ac":12,"hp":7,"hpDice":"2d6","speed":30,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Giant Rat (Diseased)","cr":0.125,"xp":25,"type":"beast","size":"Small","ac":12,"hp":7,"hpDice":"2d6","speed":30,"tags":["aquatic","beast","giantkin","vermin","wild_beast"]},
  {"name":"Giant Weasel","cr":0.125,"xp":25,"type":"beast","size":"Medium","ac":13,"hp":9,"hpDice":"2d8","speed":40,"tags":["beast","giantkin","vermin"]},
  {"name":"Guard","cr":0.125,"xp":25,"type":"humanoid","size":"Medium","ac":16,"hp":11,"hpDice":"2d8+2","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Kobold","cr":0.125,"xp":25,"type":"humanoid","size":"Small","ac":12,"hp":5,"hpDice":"2d6-2","speed":30,"tags":["humanoid","kobold"]},
  {"name":"Mastiff","cr":0.125,"xp":25,"type":"beast","size":"Medium","ac":12,"hp":5,"hpDice":"1d8+1","speed":40,"tags":["beast","wild_beast"]},
  {"name":"Merfolk","cr":0.125,"xp":25,"type":"humanoid","size":"Medium","ac":11,"hp":11,"hpDice":"2d8+2","speed":10,"tags":["aquatic","humanoid"]},
  {"name":"Mule","cr":0.125,"xp":25,"type":"beast","size":"Medium","ac":10,"hp":11,"hpDice":"2d8+2","speed":40,"tags":["beast"]},
  {"name":"Noble","cr":0.125,"xp":25,"type":"humanoid","size":"Medium","ac":15,"hp":9,"hpDice":"2d8","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Poisonous Snake","cr":0.125,"xp":25,"type":"beast","size":"Tiny","ac":13,"hp":2,"hpDice":"1d4","speed":30,"tags":["beast","wild_beast"]},
  {"name":"Pony","cr":0.125,"xp":25,"type":"beast","size":"Medium","ac":10,"hp":11,"hpDice":"2d8+2","speed":40,"tags":["beast"]},
  {"name":"Stirge","cr":0.125,"xp":25,"type":"beast","size":"Tiny","ac":14,"hp":2,"hpDice":"1d4","speed":10,"tags":["beast"]},
  {"name":"Tribal Warrior","cr":0.125,"xp":25,"type":"humanoid","size":"Medium","ac":12,"hp":11,"hpDice":"2d8+2","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Acolyte","cr":0.25,"xp":50,"type":"humanoid","size":"Medium","ac":10,"hp":9,"hpDice":"2d8","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Axe Beak","cr":0.25,"xp":50,"type":"beast","size":"Large","ac":11,"hp":19,"hpDice":"3d10+3","speed":50,"tags":["beast"]},
  {"name":"Blink Dog","cr":0.25,"xp":50,"type":"fey","size":"Medium","ac":13,"hp":22,"hpDice":"4d8+4","speed":40,"tags":["fey","fey_theme"]},
  {"name":"Boar","cr":0.25,"xp":50,"type":"beast","size":"Medium","ac":11,"hp":11,"hpDice":"2d8+2","speed":40,"tags":["beast","wild_beast"]},
  {"name":"Constrictor Snake","cr":0.25,"xp":50,"type":"beast","size":"Large","ac":12,"hp":13,"hpDice":"2d10+2","speed":30,"tags":["beast","wild_beast"]},
  {"name":"Draft Horse","cr":0.25,"xp":50,"type":"beast","size":"Large","ac":10,"hp":19,"hpDice":"3d10+3","speed":40,"tags":["beast","wild_beast"]},
  {"name":"Dretch","cr":0.25,"xp":25,"type":"fiend","size":"Small","ac":11,"hp":18,"hpDice":"4d6+4","speed":20,"tags":["demon","fiend"]},
  {"name":"Drow","cr":0.25,"xp":50,"type":"humanoid","size":"Medium","ac":15,"hp":13,"hpDice":"3d8","speed":30,"tags":["humanoid"]},
  {"name":"Elk","cr":0.25,"xp":50,"type":"beast","size":"Large","ac":10,"hp":13,"hpDice":"2d10+2","speed":50,"tags":["beast","wild_beast"]},
  {"name":"Flying Sword","cr":0.25,"xp":50,"type":"construct","size":"Small","ac":17,"hp":17,"hpDice":"5d6","speed":0,"tags":["construct"]},
  {"name":"Giant Badger","cr":0.25,"xp":50,"type":"beast","size":"Medium","ac":10,"hp":13,"hpDice":"2d8+4","speed":30,"tags":["beast","giantkin","vermin"]},
  {"name":"Giant Bat","cr":0.25,"xp":50,"type":"beast","size":"Large","ac":13,"hp":22,"hpDice":"4d10","speed":10,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Giant Centipede","cr":0.25,"xp":50,"type":"beast","size":"Small","ac":13,"hp":4,"hpDice":"1d6+1","speed":30,"tags":["beast","giantkin","vermin"]},
  {"name":"Giant Frog","cr":0.25,"xp":50,"type":"beast","size":"Medium","ac":11,"hp":18,"hpDice":"4d8","speed":30,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Giant Lizard","cr":0.25,"xp":50,"type":"beast","size":"Large","ac":12,"hp":19,"hpDice":"3d10+3","speed":30,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Giant Owl","cr":0.25,"xp":50,"type":"beast","size":"Large","ac":12,"hp":19,"hpDice":"3d10+3","speed":5,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Giant Poisonous Snake","cr":0.25,"xp":50,"type":"beast","size":"Medium","ac":14,"hp":11,"hpDice":"2d8+2","speed":30,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Giant Wolf Spider","cr":0.25,"xp":50,"type":"beast","size":"Medium","ac":13,"hp":11,"hpDice":"2d8+2","speed":40,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Goblin","cr":0.25,"xp":50,"type":"humanoid","size":"Small","ac":15,"hp":7,"hpDice":"2d6","speed":30,"tags":["goblinoid","humanoid"]},
  {"name":"Grimlock","cr":0.25,"xp":50,"type":"humanoid","size":"Medium","ac":11,"hp":11,"hpDice":"2d8+2","speed":30,"tags":["humanoid"]},
  {"name":"Panther","cr":0.25,"xp":50,"type":"beast","size":"Medium","ac":12,"hp":13,"hpDice":"3d8","speed":50,"tags":["beast","wild_beast"]},
  {"name":"Pseudodragon","cr":0.25,"xp":50,"type":"dragon","size":"Tiny","ac":13,"hp":7,"hpDice":"2d4+2","speed":15,"tags":["draconic","dragon","fey_theme"]},
  {"name":"Riding Horse","cr":0.25,"xp":25,"type":"beast","size":"Large","ac":10,"hp":13,"hpDice":"2d10+2","speed":60,"tags":["beast","wild_beast"]},
  {"name":"Skeleton","cr":0.25,"xp":50,"type":"undead","size":"Medium","ac":13,"hp":13,"hpDice":"2d8+4","speed":30,"tags":["undead","undead_theme"]},
  {"name":"Sprite","cr":0.25,"xp":50,"type":"fey","size":"Tiny","ac":15,"hp":2,"hpDice":"1d4","speed":10,"tags":["fey","fey_theme"]},
  {"name":"Steam Mephit","cr":0.25,"xp":50,"type":"elemental","size":"Small","ac":10,"hp":21,"hpDice":"6d6","speed":30,"tags":["elemental","elemental_construct"]},
  {"name":"Swarm of Bats","cr":0.25,"xp":50,"type":"swarm","size":"Medium","ac":12,"hp":22,"hpDice":"5d8","speed":0,"tags":["swarm","wild_beast"]},
  {"name":"Swarm of Rats","cr":0.25,"xp":50,"type":"swarm","size":"Medium","ac":10,"hp":24,"hpDice":"7d8-7","speed":30,"tags":["swarm","wild_beast"]},
  {"name":"Swarm of Ravens","cr":0.25,"xp":50,"type":"swarm","size":"Medium","ac":12,"hp":24,"hpDice":"7d8-7","speed":10,"tags":["swarm"]},
  {"name":"Violet Fungus","cr":0.25,"xp":50,"type":"plant","size":"Medium","ac":5,"hp":18,"hpDice":"4d8","speed":5,"tags":["plant","plant_theme"]},
  {"name":"Wolf","cr":0.25,"xp":50,"type":"beast","size":"Medium","ac":13,"hp":11,"hpDice":"2d8+2","speed":40,"tags":["beast","wild_beast"]},
  {"name":"Zombie","cr":0.25,"xp":50,"type":"undead","size":"Medium","ac":8,"hp":22,"hpDice":"3d8+9","speed":20,"tags":["ooze_theme","undead","undead_theme"]},
  {"name":"Ape","cr":0.5,"xp":100,"type":"beast","size":"Medium","ac":12,"hp":19,"hpDice":"3d8+6","speed":30,"tags":["beast","wild_beast"]},
  {"name":"Black Bear","cr":0.5,"xp":100,"type":"beast","size":"Medium","ac":11,"hp":19,"hpDice":"3d8+6","speed":40,"tags":["beast","wild_beast"]},
  {"name":"Cockatrice","cr":0.5,"xp":100,"type":"monstrosity","size":"Small","ac":11,"hp":27,"hpDice":"6d6+6","speed":20,"tags":["ice","monstrosity"]},
  {"name":"Crocodile","cr":0.5,"xp":100,"type":"beast","size":"Large","ac":12,"hp":19,"hpDice":"3d10+3","speed":20,"tags":["beast","wild_beast"]},
  {"name":"Darkmantle","cr":0.5,"xp":100,"type":"monstrosity","size":"Small","ac":11,"hp":22,"hpDice":"5d6+5","speed":10,"tags":["monstrosity"]},
  {"name":"Deep Gnome (Svirfneblin)","cr":0.5,"xp":50,"type":"humanoid","size":"Small","ac":15,"hp":16,"hpDice":"3d6+6","speed":20,"tags":["humanoid"]},
  {"name":"Dust Mephit","cr":0.5,"xp":100,"type":"elemental","size":"Small","ac":12,"hp":17,"hpDice":"5d6","speed":30,"tags":["elemental","elemental_construct"]},
  {"name":"Giant Goat","cr":0.5,"xp":100,"type":"beast","size":"Large","ac":11,"hp":19,"hpDice":"3d10+3","speed":40,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Giant Sea Horse","cr":0.5,"xp":100,"type":"beast","size":"Large","ac":13,"hp":16,"hpDice":"3d10","speed":0,"tags":["aquatic","beast","giantkin","vermin","wild_beast"]},
  {"name":"Giant Wasp","cr":0.5,"xp":100,"type":"beast","size":"Medium","ac":12,"hp":13,"hpDice":"3d8","speed":10,"tags":["beast","giantkin","vermin"]},
  {"name":"Gnoll","cr":0.5,"xp":100,"type":"humanoid","size":"Medium","ac":15,"hp":22,"hpDice":"5d8","speed":30,"tags":["gnoll","humanoid"]},
  {"name":"Gray Ooze","cr":0.5,"xp":100,"type":"ooze","size":"Medium","ac":8,"hp":22,"hpDice":"3d8+9","speed":10,"tags":["ooze","ooze_theme"]},
  {"name":"Hobgoblin","cr":0.5,"xp":100,"type":"humanoid","size":"Medium","ac":18,"hp":11,"hpDice":"2d8+2","speed":30,"tags":["goblinoid","humanoid"]},
  {"name":"Ice Mephit","cr":0.5,"xp":100,"type":"elemental","size":"Small","ac":11,"hp":21,"hpDice":"6d6","speed":30,"tags":["elemental","elemental_construct","ice"]},
  {"name":"Lizardfolk","cr":0.5,"xp":100,"type":"humanoid","size":"Medium","ac":13,"hp":22,"hpDice":"4d8+4","speed":30,"tags":["humanoid","reptilian","wild_beast"]},
  {"name":"Magma Mephit","cr":0.5,"xp":100,"type":"elemental","size":"Small","ac":11,"hp":22,"hpDice":"5d6+5","speed":30,"tags":["elemental","elemental_construct","fire"]},
  {"name":"Magmin","cr":0.5,"xp":100,"type":"elemental","size":"Small","ac":14,"hp":9,"hpDice":"2d6+2","speed":30,"tags":["elemental","fire"]},
  {"name":"Orc","cr":0.5,"xp":100,"type":"humanoid","size":"Medium","ac":13,"hp":15,"hpDice":"2d8+6","speed":30,"tags":["humanoid","orc"]},
  {"name":"Reef Shark","cr":0.5,"xp":100,"type":"beast","size":"Medium","ac":12,"hp":22,"hpDice":"4d8+4","speed":40,"tags":["aquatic","beast","wild_beast"]},
  {"name":"Rust Monster","cr":0.5,"xp":100,"type":"monstrosity","size":"Medium","ac":14,"hp":27,"hpDice":"5d8+5","speed":40,"tags":["monstrosity"]},
  {"name":"Sahuagin","cr":0.5,"xp":100,"type":"humanoid","size":"Medium","ac":12,"hp":22,"hpDice":"4d8+4","speed":30,"tags":["aquatic","humanoid"]},
  {"name":"Satyr","cr":0.5,"xp":100,"type":"fey","size":"Medium","ac":14,"hp":31,"hpDice":"7d8","speed":40,"tags":["fey","fey_theme"]},
  {"name":"Scout","cr":0.5,"xp":100,"type":"humanoid","size":"Medium","ac":13,"hp":16,"hpDice":"3d8+3","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Shadow","cr":0.5,"xp":100,"type":"undead","size":"Medium","ac":12,"hp":16,"hpDice":"3d8+3","speed":40,"tags":["undead","undead_theme"]},
  {"name":"Swarm of Beetles","cr":0.5,"xp":100,"type":"swarm","size":"Medium","ac":12,"hp":22,"hpDice":"5d8","speed":20,"tags":["swarm","vermin"]},
  {"name":"Swarm of Centipedes","cr":0.5,"xp":100,"type":"swarm","size":"Medium","ac":12,"hp":22,"hpDice":"5d8","speed":20,"tags":["swarm","vermin"]},
  {"name":"Swarm of Insects","cr":0.5,"xp":100,"type":"swarm","size":"Medium","ac":12,"hp":22,"hpDice":"5d8","speed":20,"tags":["swarm","vermin"]},
  {"name":"Swarm of Spiders","cr":0.5,"xp":100,"type":"swarm","size":"Medium","ac":12,"hp":22,"hpDice":"5d8","speed":20,"tags":["swarm","vermin"]},
  {"name":"Swarm of Wasps","cr":0.5,"xp":100,"type":"swarm","size":"Medium","ac":12,"hp":22,"hpDice":"5d8","speed":5,"tags":["swarm","vermin"]},
  {"name":"Thug","cr":0.5,"xp":100,"type":"humanoid","size":"Medium","ac":11,"hp":32,"hpDice":"5d8+10","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Warhorse","cr":0.5,"xp":100,"type":"beast","size":"Large","ac":11,"hp":19,"hpDice":"3d10+3","speed":60,"tags":["beast","wild_beast"]},
  {"name":"Warhorse Skeleton","cr":0.5,"xp":100,"type":"undead","size":"Large","ac":13,"hp":22,"hpDice":"3d10+6","speed":60,"tags":["undead","undead_theme","wild_beast"]},
  {"name":"Worg","cr":0.5,"xp":100,"type":"monstrosity","size":"Large","ac":13,"hp":26,"hpDice":"4d10+4","speed":50,"tags":["monstrosity"]},
  {"name":"Animated Armor","cr":1,"xp":200,"type":"construct","size":"Medium","ac":18,"hp":33,"hpDice":"6d8+6","speed":25,"tags":["construct","construct_theme"]},
  {"name":"Brass Dragon Wyrmling","cr":1,"xp":100,"type":"dragon","size":"Medium","ac":16,"hp":16,"hpDice":"3d8+3","speed":30,"tags":["draconic","dragon"]},
  {"name":"Brown Bear","cr":1,"xp":200,"type":"beast","size":"Large","ac":11,"hp":34,"hpDice":"4d10+12","speed":40,"tags":["beast","wild_beast"]},
  {"name":"Bugbear","cr":1,"xp":200,"type":"humanoid","size":"Medium","ac":16,"hp":27,"hpDice":"5d8+5","speed":30,"tags":["goblinoid","humanoid","wild_beast"]},
  {"name":"Copper Dragon Wyrmling","cr":1,"xp":200,"type":"dragon","size":"Medium","ac":16,"hp":22,"hpDice":"4d8+4","speed":30,"tags":["draconic","dragon"]},
  {"name":"Death Dog","cr":1,"xp":200,"type":"monstrosity","size":"Medium","ac":12,"hp":39,"hpDice":"6d8+12","speed":40,"tags":["monstrosity","undead_theme"]},
  {"name":"Dire Wolf","cr":1,"xp":200,"type":"beast","size":"Large","ac":14,"hp":37,"hpDice":"5d10+10","speed":50,"tags":["beast","wild_beast"]},
  {"name":"Dryad","cr":1,"xp":200,"type":"fey","size":"Medium","ac":11,"hp":22,"hpDice":"5d8","speed":30,"tags":["fey","fey_theme"]},
  {"name":"Duergar","cr":1,"xp":200,"type":"humanoid","size":"Medium","ac":16,"hp":26,"hpDice":"4d8+8","speed":25,"tags":["humanoid"]},
  {"name":"Ghoul","cr":1,"xp":200,"type":"undead","size":"Medium","ac":12,"hp":22,"hpDice":"5d8","speed":30,"tags":["undead","undead_theme"]},
  {"name":"Giant Eagle","cr":1,"xp":200,"type":"beast","size":"Large","ac":13,"hp":26,"hpDice":"4d10+4","speed":10,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Giant Hyena","cr":1,"xp":200,"type":"beast","size":"Large","ac":12,"hp":45,"hpDice":"6d10+12","speed":50,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Giant Octopus","cr":1,"xp":200,"type":"beast","size":"Large","ac":11,"hp":52,"hpDice":"8d10+8","speed":10,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Giant Spider","cr":1,"xp":200,"type":"beast","size":"Large","ac":14,"hp":26,"hpDice":"4d10+4","speed":30,"tags":["beast","giantkin","vermin"]},
  {"name":"Giant Toad","cr":1,"xp":200,"type":"beast","size":"Large","ac":11,"hp":39,"hpDice":"6d10+6","speed":20,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Giant Vulture","cr":1,"xp":200,"type":"beast","size":"Large","ac":10,"hp":22,"hpDice":"3d10+6","speed":10,"tags":["beast","giantkin","vermin"]},
  {"name":"Harpy","cr":1,"xp":200,"type":"monstrosity","size":"Medium","ac":11,"hp":38,"hpDice":"7d8+7","speed":20,"tags":["monstrosity"]},
  {"name":"Hippogriff","cr":1,"xp":200,"type":"monstrosity","size":"Large","ac":11,"hp":19,"hpDice":"3d10+3","speed":40,"tags":["monstrosity"]},
  {"name":"Imp","cr":1,"xp":200,"type":"fiend","size":"Tiny","ac":13,"hp":10,"hpDice":"3d4+3","speed":20,"tags":["devil","fiend"]},
  {"name":"Lion","cr":1,"xp":200,"type":"beast","size":"Large","ac":12,"hp":26,"hpDice":"4d10+4","speed":50,"tags":["beast","wild_beast"]},
  {"name":"Quasit","cr":1,"xp":200,"type":"fiend","size":"Tiny","ac":13,"hp":7,"hpDice":"3d4","speed":40,"tags":["demon","fiend"]},
  {"name":"Specter","cr":1,"xp":200,"type":"undead","size":"Medium","ac":12,"hp":22,"hpDice":"5d8","speed":0,"tags":["undead","undead_theme"]},
  {"name":"Spy","cr":1,"xp":200,"type":"humanoid","size":"Medium","ac":12,"hp":27,"hpDice":"6d8","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Swarm of Quippers","cr":1,"xp":200,"type":"swarm","size":"Medium","ac":13,"hp":28,"hpDice":"8d8-8","speed":0,"tags":["swarm"]},
  {"name":"Tiger","cr":1,"xp":200,"type":"beast","size":"Large","ac":12,"hp":37,"hpDice":"5d10+10","speed":40,"tags":["beast","wild_beast"]},
  {"name":"Ankheg","cr":2,"xp":450,"type":"monstrosity","size":"Large","ac":14,"hp":39,"hpDice":"6d10+6","speed":30,"tags":["monstrosity"]},
  {"name":"Awakened Tree","cr":2,"xp":450,"type":"plant","size":"Huge","ac":13,"hp":59,"hpDice":"7d12+14","speed":20,"tags":["plant","plant_theme"]},
  {"name":"Azer","cr":2,"xp":450,"type":"elemental","size":"Medium","ac":15,"hp":39,"hpDice":"6d8+12","speed":30,"tags":["elemental","fire"]},
  {"name":"Bandit Captain","cr":2,"xp":450,"type":"humanoid","size":"Medium","ac":15,"hp":65,"hpDice":"10d8+20","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Berserker","cr":2,"xp":450,"type":"humanoid","size":"Medium","ac":13,"hp":67,"hpDice":"9d8+27","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Black Dragon Wyrmling","cr":2,"xp":450,"type":"dragon","size":"Medium","ac":17,"hp":33,"hpDice":"6d8+6","speed":30,"tags":["draconic","dragon"]},
  {"name":"Bronze Dragon Wyrmling","cr":2,"xp":450,"type":"dragon","size":"Medium","ac":17,"hp":32,"hpDice":"5d8+10","speed":30,"tags":["draconic","dragon"]},
  {"name":"Centaur","cr":2,"xp":450,"type":"monstrosity","size":"Large","ac":12,"hp":45,"hpDice":"6d10+12","speed":50,"tags":["monstrosity"]},
  {"name":"Cult Fanatic","cr":2,"xp":450,"type":"humanoid","size":"Medium","ac":13,"hp":22,"hpDice":"6d8-5","speed":30,"tags":["humanoid"]},
  {"name":"Druid","cr":2,"xp":450,"type":"humanoid","size":"Medium","ac":11,"hp":27,"hpDice":"5d8+5","speed":30,"tags":["humanoid"]},
  {"name":"Ettercap","cr":2,"xp":450,"type":"monstrosity","size":"Medium","ac":13,"hp":44,"hpDice":"8d8+8","speed":30,"tags":["monstrosity","vermin"]},
  {"name":"Gargoyle","cr":2,"xp":450,"type":"elemental","size":"Medium","ac":15,"hp":52,"hpDice":"7d8+21","speed":30,"tags":["elemental","elemental_construct"]},
  {"name":"Gelatinous Cube","cr":2,"xp":450,"type":"ooze","size":"Large","ac":6,"hp":84,"hpDice":"8d10+40","speed":15,"tags":["ooze","ooze_theme"]},
  {"name":"Ghast","cr":2,"xp":450,"type":"undead","size":"Medium","ac":13,"hp":36,"hpDice":"8d8","speed":30,"tags":["undead","undead_theme"]},
  {"name":"Giant Boar","cr":2,"xp":450,"type":"beast","size":"Large","ac":12,"hp":42,"hpDice":"5d10+15","speed":40,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Giant Constrictor Snake","cr":2,"xp":450,"type":"beast","size":"Huge","ac":12,"hp":60,"hpDice":"8d12+8","speed":30,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Giant Elk","cr":2,"xp":450,"type":"beast","size":"Huge","ac":14,"hp":42,"hpDice":"5d12+10","speed":60,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Gibbering Mouther","cr":2,"xp":450,"type":"aberration","size":"Medium","ac":9,"hp":67,"hpDice":"9d8+27","speed":10,"tags":["aberrant","aberration"]},
  {"name":"Green Dragon Wyrmling","cr":2,"xp":450,"type":"dragon","size":"Medium","ac":17,"hp":38,"hpDice":"7d8+7","speed":30,"tags":["draconic","dragon"]},
  {"name":"Grick","cr":2,"xp":450,"type":"monstrosity","size":"Medium","ac":14,"hp":27,"hpDice":"6d8","speed":30,"tags":["monstrosity"]},
  {"name":"Griffon","cr":2,"xp":450,"type":"monstrosity","size":"Large","ac":12,"hp":59,"hpDice":"7d10+21","speed":30,"tags":["monstrosity"]},
  {"name":"Hunter Shark","cr":2,"xp":450,"type":"beast","size":"Large","ac":12,"hp":45,"hpDice":"6d10+12","speed":40,"tags":["beast","wild_beast"]},
  {"name":"Merrow","cr":2,"xp":450,"type":"monstrosity","size":"Large","ac":13,"hp":45,"hpDice":"6d10+12","speed":10,"tags":["aquatic","monstrosity"]},
  {"name":"Mimic","cr":2,"xp":450,"type":"monstrosity","size":"Medium","ac":12,"hp":58,"hpDice":"9d8+18","speed":15,"tags":["monstrosity"]},
  {"name":"Minotaur Skeleton","cr":2,"xp":450,"type":"undead","size":"Large","ac":12,"hp":67,"hpDice":"9d10+18","speed":40,"tags":["undead","undead_theme"]},
  {"name":"Ochre Jelly","cr":2,"xp":450,"type":"ooze","size":"Large","ac":8,"hp":45,"hpDice":"6d10+12","speed":10,"tags":["ooze","ooze_theme"]},
  {"name":"Ogre","cr":2,"xp":450,"type":"giant","size":"Large","ac":11,"hp":59,"hpDice":"7d10+21","speed":40,"tags":["giant","giantkin"]},
  {"name":"Ogre Zombie","cr":2,"xp":450,"type":"undead","size":"Large","ac":8,"hp":85,"hpDice":"9d10+36","speed":30,"tags":["giantkin","ooze_theme","undead","undead_theme"]},
  {"name":"Pegasus","cr":2,"xp":450,"type":"celestial","size":"Large","ac":12,"hp":59,"hpDice":"7d10+21","speed":60,"tags":["celestial","celestial_theme"]},
  {"name":"Plesiosaurus","cr":2,"xp":450,"type":"beast","size":"Large","ac":13,"hp":68,"hpDice":"8d10+24","speed":20,"tags":["beast"]},
  {"name":"Polar Bear","cr":2,"xp":450,"type":"beast","size":"Large","ac":12,"hp":42,"hpDice":"5d10+15","speed":40,"tags":["beast","wild_beast"]},
  {"name":"Priest","cr":2,"xp":450,"type":"humanoid","size":"Medium","ac":13,"hp":27,"hpDice":"5d8+5","speed":25,"tags":["humanoid","humanoid_npc"]},
  {"name":"Rhinoceros","cr":2,"xp":450,"type":"beast","size":"Large","ac":11,"hp":45,"hpDice":"6d10+12","speed":40,"tags":["beast"]},
  {"name":"Rug of Smothering","cr":2,"xp":450,"type":"construct","size":"Large","ac":12,"hp":33,"hpDice":"6d10","speed":10,"tags":["construct"]},
  {"name":"Saber-Toothed Tiger","cr":2,"xp":450,"type":"beast","size":"Large","ac":12,"hp":52,"hpDice":"7d10+14","speed":40,"tags":["beast","wild_beast"]},
  {"name":"Sea Hag","cr":2,"xp":450,"type":"fey","size":"Medium","ac":14,"hp":52,"hpDice":"7d8+21","speed":30,"tags":["aquatic","fey","fey_theme"]},
  {"name":"Silver Dragon Wyrmling","cr":2,"xp":450,"type":"dragon","size":"Medium","ac":17,"hp":45,"hpDice":"6d8+18","speed":30,"tags":["draconic","dragon"]},
  {"name":"Swarm of Poisonous Snakes","cr":2,"xp":450,"type":"swarm","size":"Medium","ac":14,"hp":36,"hpDice":"8d8","speed":30,"tags":["swarm","wild_beast"]},
  {"name":"Wererat, Human Form","cr":2,"xp":450,"type":"humanoid","size":"Medium","ac":12,"hp":33,"hpDice":"6d8+6","speed":30,"tags":["humanoid","lycanthrope","wild_beast"]},
  {"name":"Wererat, Hybrid Form","cr":2,"xp":450,"type":"humanoid","size":"Medium","ac":12,"hp":33,"hpDice":"6d8+6","speed":30,"tags":["humanoid","lycanthrope","wild_beast"]},
  {"name":"Wererat, Rat Form","cr":2,"xp":450,"type":"humanoid","size":"Medium","ac":12,"hp":33,"hpDice":"6d8+6","speed":30,"tags":["humanoid","lycanthrope","wild_beast"]},
  {"name":"White Dragon Wyrmling","cr":2,"xp":450,"type":"dragon","size":"Medium","ac":16,"hp":32,"hpDice":"5d8+10","speed":30,"tags":["draconic","dragon","ice"]},
  {"name":"Will-o'-Wisp","cr":2,"xp":450,"type":"undead","size":"Tiny","ac":19,"hp":22,"hpDice":"9d4","speed":0,"tags":["undead","undead_theme"]},
  {"name":"Basilisk","cr":3,"xp":700,"type":"monstrosity","size":"Medium","ac":12,"hp":52,"hpDice":"8d8+16","speed":20,"tags":["monstrosity"]},
  {"name":"Bearded Devil","cr":3,"xp":700,"type":"fiend","size":"Medium","ac":13,"hp":52,"hpDice":"8d8+16","speed":30,"tags":["devil","fiend","wild_beast"]},
  {"name":"Blue Dragon Wyrmling","cr":3,"xp":700,"type":"dragon","size":"Medium","ac":17,"hp":52,"hpDice":"8d8+16","speed":30,"tags":["draconic","dragon"]},
  {"name":"Doppelganger","cr":3,"xp":700,"type":"monstrosity","size":"Medium","ac":14,"hp":52,"hpDice":"8d8+16","speed":30,"tags":["monstrosity"]},
  {"name":"Giant Scorpion","cr":3,"xp":700,"type":"beast","size":"Large","ac":15,"hp":52,"hpDice":"7d10+14","speed":40,"tags":["beast","giantkin","vermin"]},
  {"name":"Gold Dragon Wyrmling","cr":3,"xp":700,"type":"dragon","size":"Medium","ac":17,"hp":60,"hpDice":"8d8+24","speed":30,"tags":["draconic","dragon"]},
  {"name":"Green Hag","cr":3,"xp":700,"type":"fey","size":"Medium","ac":17,"hp":82,"hpDice":"11d8+33","speed":30,"tags":["fey","fey_theme"]},
  {"name":"Hell Hound","cr":3,"xp":700,"type":"fiend","size":"Medium","ac":15,"hp":45,"hpDice":"7d8+14","speed":50,"tags":["fiend","fire"]},
  {"name":"Killer Whale","cr":3,"xp":700,"type":"beast","size":"Huge","ac":12,"hp":90,"hpDice":"12d12+12","speed":60,"tags":["beast"]},
  {"name":"Knight","cr":3,"xp":700,"type":"humanoid","size":"Medium","ac":18,"hp":52,"hpDice":"8d8+16","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Manticore","cr":3,"xp":700,"type":"monstrosity","size":"Large","ac":14,"hp":68,"hpDice":"8d10+24","speed":30,"tags":["monstrosity"]},
  {"name":"Minotaur","cr":3,"xp":700,"type":"monstrosity","size":"Large","ac":14,"hp":76,"hpDice":"9d10+27","speed":40,"tags":["monstrosity"]},
  {"name":"Mummy","cr":3,"xp":700,"type":"undead","size":"Medium","ac":11,"hp":58,"hpDice":"9d8+18","speed":20,"tags":["undead","undead_theme"]},
  {"name":"Nightmare","cr":3,"xp":700,"type":"fiend","size":"Large","ac":13,"hp":68,"hpDice":"8d10+24","speed":60,"tags":["fiend"]},
  {"name":"Owlbear","cr":3,"xp":700,"type":"monstrosity","size":"Large","ac":13,"hp":59,"hpDice":"7d10+21","speed":40,"tags":["monstrosity","wild_beast"]},
  {"name":"Phase Spider","cr":3,"xp":700,"type":"monstrosity","size":"Large","ac":13,"hp":32,"hpDice":"5d10+5","speed":30,"tags":["monstrosity","vermin"]},
  {"name":"Veteran","cr":3,"xp":700,"type":"humanoid","size":"Medium","ac":17,"hp":58,"hpDice":"9d8+18","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Werewolf, Human Form","cr":3,"xp":700,"type":"humanoid","size":"Medium","ac":11,"hp":58,"hpDice":"9d8+18","speed":30,"tags":["humanoid","lycanthrope","wild_beast"]},
  {"name":"Werewolf, Hybrid Form","cr":3,"xp":700,"type":"humanoid","size":"Medium","ac":12,"hp":58,"hpDice":"9d8+18","speed":30,"tags":["humanoid","lycanthrope","wild_beast"]},
  {"name":"Werewolf, Wolf Form","cr":3,"xp":700,"type":"humanoid","size":"Medium","ac":12,"hp":58,"hpDice":"9d8+18","speed":40,"tags":["humanoid","lycanthrope","wild_beast"]},
  {"name":"Wight","cr":3,"xp":700,"type":"undead","size":"Medium","ac":14,"hp":45,"hpDice":"6d8+18","speed":30,"tags":["undead","undead_theme"]},
  {"name":"Winter Wolf","cr":3,"xp":700,"type":"monstrosity","size":"Large","ac":13,"hp":75,"hpDice":"10d10+20","speed":50,"tags":["ice","monstrosity","wild_beast"]},
  {"name":"Black Pudding","cr":4,"xp":1100,"type":"ooze","size":"Large","ac":7,"hp":85,"hpDice":"10d10+30","speed":20,"tags":["ooze","ooze_theme"]},
  {"name":"Chuul","cr":4,"xp":1100,"type":"aberration","size":"Large","ac":16,"hp":93,"hpDice":"11d10+33","speed":30,"tags":["aberrant","aberration"]},
  {"name":"Couatl","cr":4,"xp":1100,"type":"celestial","size":"Medium","ac":19,"hp":97,"hpDice":"13d8+39","speed":30,"tags":["celestial","celestial_theme"]},
  {"name":"Elephant","cr":4,"xp":1100,"type":"beast","size":"Huge","ac":12,"hp":76,"hpDice":"8d12+24","speed":40,"tags":["beast","vermin"]},
  {"name":"Ettin","cr":4,"xp":1100,"type":"giant","size":"Large","ac":12,"hp":85,"hpDice":"10d10+30","speed":40,"tags":["giant","giantkin"]},
  {"name":"Ghost","cr":4,"xp":1100,"type":"undead","size":"Medium","ac":11,"hp":45,"hpDice":"10d8","speed":0,"tags":["undead","undead_theme"]},
  {"name":"Lamia","cr":4,"xp":1100,"type":"monstrosity","size":"Large","ac":13,"hp":97,"hpDice":"13d10+26","speed":30,"tags":["monstrosity"]},
  {"name":"Red Dragon Wyrmling","cr":4,"xp":1100,"type":"dragon","size":"Medium","ac":17,"hp":75,"hpDice":"10d8+30","speed":30,"tags":["draconic","dragon","fire"]},
  {"name":"Succubus/Incubus","cr":4,"xp":1100,"type":"fiend","size":"Medium","ac":15,"hp":66,"hpDice":"12d8+12","speed":30,"tags":["fiend"]},
  {"name":"Wereboar, Boar Form","cr":4,"xp":1100,"type":"humanoid","size":"Medium","ac":11,"hp":78,"hpDice":"12d8+24","speed":40,"tags":["humanoid","lycanthrope","wild_beast"]},
  {"name":"Wereboar, Human Form","cr":4,"xp":1100,"type":"humanoid","size":"Medium","ac":10,"hp":78,"hpDice":"12d8+24","speed":30,"tags":["humanoid","lycanthrope","wild_beast"]},
  {"name":"Wereboar, Hybrid Form","cr":4,"xp":1100,"type":"humanoid","size":"Medium","ac":11,"hp":78,"hpDice":"12d8+24","speed":30,"tags":["humanoid","lycanthrope","wild_beast"]},
  {"name":"Weretiger, Human Form","cr":4,"xp":1100,"type":"humanoid","size":"Medium","ac":12,"hp":120,"hpDice":"16d8+48","speed":30,"tags":["humanoid","lycanthrope","wild_beast"]},
  {"name":"Weretiger, Hybrid Form","cr":4,"xp":1100,"type":"humanoid","size":"Medium","ac":12,"hp":120,"hpDice":"16d8+48","speed":30,"tags":["humanoid","lycanthrope","wild_beast"]},
  {"name":"Weretiger, Tiger Form","cr":4,"xp":1100,"type":"humanoid","size":"Medium","ac":12,"hp":120,"hpDice":"16d8+48","speed":40,"tags":["humanoid","lycanthrope","wild_beast"]},
  {"name":"Air Elemental","cr":5,"xp":1800,"type":"elemental","size":"Large","ac":15,"hp":90,"hpDice":"12d10+24","speed":90,"tags":["elemental","elemental_construct"]},
  {"name":"Barbed Devil","cr":5,"xp":1800,"type":"fiend","size":"Medium","ac":15,"hp":110,"hpDice":"13d8+52","speed":30,"tags":["devil","fiend"]},
  {"name":"Bulette","cr":5,"xp":1800,"type":"monstrosity","size":"Large","ac":17,"hp":94,"hpDice":"9d10+45","speed":40,"tags":["monstrosity"]},
  {"name":"Earth Elemental","cr":5,"xp":1800,"type":"elemental","size":"Large","ac":17,"hp":126,"hpDice":"12d10+60","speed":30,"tags":["elemental","elemental_construct"]},
  {"name":"Fire Elemental","cr":5,"xp":1800,"type":"elemental","size":"Large","ac":13,"hp":102,"hpDice":"12d10+36","speed":50,"tags":["elemental","elemental_construct","fire"]},
  {"name":"Flesh Golem","cr":5,"xp":1800,"type":"construct","size":"Medium","ac":9,"hp":93,"hpDice":"11d8+44","speed":30,"tags":["construct","construct_theme","elemental_construct"]},
  {"name":"Giant Crocodile","cr":5,"xp":1800,"type":"beast","size":"Huge","ac":14,"hp":85,"hpDice":"9d12+27","speed":30,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Giant Shark","cr":5,"xp":1800,"type":"beast","size":"Huge","ac":13,"hp":126,"hpDice":"11d12+55","speed":50,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Gladiator","cr":5,"xp":1800,"type":"humanoid","size":"Medium","ac":16,"hp":112,"hpDice":"15d8+45","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Gorgon","cr":5,"xp":1800,"type":"monstrosity","size":"Large","ac":19,"hp":114,"hpDice":"12d10+48","speed":40,"tags":["monstrosity"]},
  {"name":"Half-Red Dragon Veteran","cr":5,"xp":1800,"type":"humanoid","size":"Medium","ac":18,"hp":65,"hpDice":"10d8+20","speed":30,"tags":["draconic","fire","humanoid","humanoid_npc"]},
  {"name":"Hill Giant","cr":5,"xp":1800,"type":"giant","size":"Huge","ac":13,"hp":105,"hpDice":"10d12+40","speed":40,"tags":["giant","giantkin","vermin"]},
  {"name":"Night Hag","cr":5,"xp":1800,"type":"fiend","size":"Medium","ac":17,"hp":112,"hpDice":"15d8+45","speed":30,"tags":["fey_theme","fiend"]},
  {"name":"Otyugh","cr":5,"xp":1800,"type":"aberration","size":"Large","ac":14,"hp":114,"hpDice":"12d10+48","speed":30,"tags":["aberrant","aberration"]},
  {"name":"Roper","cr":5,"xp":1800,"type":"monstrosity","size":"Large","ac":20,"hp":93,"hpDice":"11d10+33","speed":10,"tags":["monstrosity"]},
  {"name":"Salamander","cr":5,"xp":1800,"type":"elemental","size":"Large","ac":15,"hp":90,"hpDice":"12d10+24","speed":30,"tags":["elemental","fire"]},
  {"name":"Shambling Mound","cr":5,"xp":1800,"type":"plant","size":"Large","ac":15,"hp":136,"hpDice":"16d10+48","speed":20,"tags":["plant","plant_theme"]},
  {"name":"Triceratops","cr":5,"xp":1800,"type":"beast","size":"Huge","ac":13,"hp":95,"hpDice":"10d12+30","speed":50,"tags":["beast","ice","wild_beast"]},
  {"name":"Troll","cr":5,"xp":1800,"type":"giant","size":"Large","ac":15,"hp":84,"hpDice":"8d10+40","speed":30,"tags":["giant","giantkin"]},
  {"name":"Unicorn","cr":5,"xp":1800,"type":"celestial","size":"Large","ac":12,"hp":67,"hpDice":"9d10+18","speed":50,"tags":["celestial","celestial_theme"]},
  {"name":"Vampire Spawn","cr":5,"xp":1800,"type":"undead","size":"Medium","ac":15,"hp":82,"hpDice":"11d8+33","speed":30,"tags":["undead","undead_theme"]},
  {"name":"Water Elemental","cr":5,"xp":1800,"type":"elemental","size":"Large","ac":14,"hp":114,"hpDice":"12d10+48","speed":30,"tags":["aquatic","elemental","elemental_construct"]},
  {"name":"Werebear, Bear Form","cr":5,"xp":1800,"type":"humanoid","size":"Medium","ac":11,"hp":135,"hpDice":"18d8+54","speed":40,"tags":["humanoid","lycanthrope","wild_beast"]},
  {"name":"Werebear, Human Form","cr":5,"xp":1800,"type":"humanoid","size":"Medium","ac":10,"hp":135,"hpDice":"18d8+54","speed":30,"tags":["humanoid","lycanthrope","wild_beast"]},
  {"name":"Werebear, Hybrid Form","cr":5,"xp":1800,"type":"humanoid","size":"Medium","ac":11,"hp":135,"hpDice":"18d8+54","speed":40,"tags":["humanoid","lycanthrope","wild_beast"]},
  {"name":"Wraith","cr":5,"xp":1800,"type":"undead","size":"Medium","ac":13,"hp":67,"hpDice":"9d8+27","speed":0,"tags":["undead","undead_theme"]},
  {"name":"Xorn","cr":5,"xp":1800,"type":"elemental","size":"Medium","ac":19,"hp":73,"hpDice":"7d8+42","speed":20,"tags":["elemental","elemental_construct"]},
  {"name":"Chimera","cr":6,"xp":2300,"type":"monstrosity","size":"Large","ac":14,"hp":114,"hpDice":"12d10+48","speed":30,"tags":["monstrosity"]},
  {"name":"Drider","cr":6,"xp":2300,"type":"monstrosity","size":"Large","ac":19,"hp":123,"hpDice":"13d10+52","speed":30,"tags":["monstrosity"]},
  {"name":"Invisible Stalker","cr":6,"xp":2300,"type":"elemental","size":"Medium","ac":14,"hp":104,"hpDice":"16d8+32","speed":50,"tags":["elemental"]},
  {"name":"Mage","cr":6,"xp":2300,"type":"humanoid","size":"Medium","ac":12,"hp":40,"hpDice":"9d8","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Mammoth","cr":6,"xp":2300,"type":"beast","size":"Huge","ac":13,"hp":126,"hpDice":"11d12+55","speed":40,"tags":["beast"]},
  {"name":"Medusa","cr":6,"xp":2300,"type":"monstrosity","size":"Medium","ac":15,"hp":127,"hpDice":"17d8+51","speed":30,"tags":["monstrosity"]},
  {"name":"Vrock","cr":6,"xp":2300,"type":"fiend","size":"Large","ac":15,"hp":104,"hpDice":"11d10+44","speed":40,"tags":["demon","fiend"]},
  {"name":"Wyvern","cr":6,"xp":2300,"type":"dragon","size":"Large","ac":13,"hp":110,"hpDice":"13d10+39","speed":20,"tags":["draconic","dragon"]},
  {"name":"Young Brass Dragon","cr":6,"xp":2300,"type":"dragon","size":"Large","ac":17,"hp":110,"hpDice":"13d10+39","speed":40,"tags":["draconic","dragon"]},
  {"name":"Young White Dragon","cr":6,"xp":2300,"type":"dragon","size":"Large","ac":17,"hp":133,"hpDice":"14d10+56","speed":40,"tags":["draconic","dragon","ice"]},
  {"name":"Giant Ape","cr":7,"xp":2900,"type":"beast","size":"Huge","ac":12,"hp":157,"hpDice":"15d12+60","speed":40,"tags":["beast","giantkin","vermin","wild_beast"]},
  {"name":"Oni","cr":7,"xp":2900,"type":"giant","size":"Large","ac":16,"hp":110,"hpDice":"13d10+39","speed":30,"tags":["giant","giantkin"]},
  {"name":"Shield Guardian","cr":7,"xp":2900,"type":"construct","size":"Large","ac":17,"hp":142,"hpDice":"15d10+60","speed":30,"tags":["construct","construct_theme","humanoid_npc"]},
  {"name":"Stone Giant","cr":7,"xp":2900,"type":"giant","size":"Huge","ac":17,"hp":126,"hpDice":"11d12+55","speed":40,"tags":["giant","giantkin","vermin"]},
  {"name":"Young Black Dragon","cr":7,"xp":2900,"type":"dragon","size":"Large","ac":18,"hp":127,"hpDice":"15d10+45","speed":40,"tags":["draconic","dragon"]},
  {"name":"Young Copper Dragon","cr":7,"xp":2900,"type":"dragon","size":"Large","ac":17,"hp":119,"hpDice":"14d10+42","speed":40,"tags":["draconic","dragon"]},
  {"name":"Assassin","cr":8,"xp":3900,"type":"humanoid","size":"Medium","ac":15,"hp":78,"hpDice":"12d8+24","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Chain Devil","cr":8,"xp":3900,"type":"fiend","size":"Medium","ac":16,"hp":85,"hpDice":"10d8+40","speed":30,"tags":["devil","fiend"]},
  {"name":"Cloaker","cr":8,"xp":3900,"type":"aberration","size":"Large","ac":14,"hp":78,"hpDice":"12d10+12","speed":10,"tags":["aberrant","aberration"]},
  {"name":"Frost Giant","cr":8,"xp":3900,"type":"giant","size":"Huge","ac":15,"hp":138,"hpDice":"12d12+60","speed":40,"tags":["giant","giantkin","ice","vermin"]},
  {"name":"Hezrou","cr":8,"xp":3900,"type":"fiend","size":"Large","ac":16,"hp":136,"hpDice":"13d10+65","speed":30,"tags":["demon","fiend"]},
  {"name":"Hydra","cr":8,"xp":3900,"type":"monstrosity","size":"Huge","ac":15,"hp":172,"hpDice":"15d12+75","speed":30,"tags":["aquatic","monstrosity"]},
  {"name":"Spirit Naga","cr":8,"xp":3900,"type":"monstrosity","size":"Large","ac":15,"hp":75,"hpDice":"10d10+20","speed":40,"tags":["monstrosity"]},
  {"name":"Tyrannosaurus Rex","cr":8,"xp":3900,"type":"beast","size":"Huge","ac":13,"hp":136,"hpDice":"13d12+52","speed":50,"tags":["beast"]},
  {"name":"Young Bronze Dragon","cr":8,"xp":3900,"type":"dragon","size":"Large","ac":18,"hp":142,"hpDice":"15d10+60","speed":40,"tags":["draconic","dragon"]},
  {"name":"Young Green Dragon","cr":8,"xp":3900,"type":"dragon","size":"Large","ac":18,"hp":136,"hpDice":"16d10+48","speed":40,"tags":["draconic","dragon"]},
  {"name":"Bone Devil","cr":9,"xp":5000,"type":"fiend","size":"Large","ac":19,"hp":142,"hpDice":"15d10+60","speed":40,"tags":["devil","fiend"]},
  {"name":"Clay Golem","cr":9,"xp":5000,"type":"construct","size":"Large","ac":14,"hp":133,"hpDice":"14d10+56","speed":20,"tags":["construct","construct_theme","elemental_construct"]},
  {"name":"Cloud Giant","cr":9,"xp":5000,"type":"giant","size":"Huge","ac":14,"hp":200,"hpDice":"16d12+96","speed":40,"tags":["giant","giantkin","vermin"]},
  {"name":"Fire Giant","cr":9,"xp":5000,"type":"giant","size":"Huge","ac":18,"hp":162,"hpDice":"13d12+78","speed":30,"tags":["fire","giant","giantkin","vermin"]},
  {"name":"Glabrezu","cr":9,"xp":5000,"type":"fiend","size":"Large","ac":17,"hp":157,"hpDice":"15d10+75","speed":40,"tags":["demon","fiend"]},
  {"name":"Treant","cr":9,"xp":5000,"type":"plant","size":"Huge","ac":16,"hp":138,"hpDice":"12d12+60","speed":30,"tags":["plant","plant_theme","vermin"]},
  {"name":"Young Blue Dragon","cr":9,"xp":5000,"type":"dragon","size":"Large","ac":18,"hp":152,"hpDice":"16d10+64","speed":40,"tags":["draconic","dragon"]},
  {"name":"Young Silver Dragon","cr":9,"xp":5000,"type":"dragon","size":"Large","ac":18,"hp":168,"hpDice":"16d10+80","speed":40,"tags":["draconic","dragon"]},
  {"name":"Aboleth","cr":10,"xp":5900,"type":"aberration","size":"Large","ac":17,"hp":135,"hpDice":"18d10+36","speed":10,"tags":["aberrant","aberration"]},
  {"name":"Deva","cr":10,"xp":5900,"type":"celestial","size":"Medium","ac":17,"hp":136,"hpDice":"16d8+64","speed":30,"tags":["celestial","celestial_theme"]},
  {"name":"Guardian Naga","cr":10,"xp":5900,"type":"monstrosity","size":"Large","ac":18,"hp":127,"hpDice":"15d10+45","speed":40,"tags":["humanoid_npc","monstrosity"]},
  {"name":"Stone Golem","cr":10,"xp":5900,"type":"construct","size":"Large","ac":17,"hp":178,"hpDice":"17d10+85","speed":30,"tags":["construct","construct_theme","elemental_construct"]},
  {"name":"Young Gold Dragon","cr":10,"xp":5900,"type":"dragon","size":"Large","ac":18,"hp":178,"hpDice":"17d10+85","speed":40,"tags":["draconic","dragon"]},
  {"name":"Young Red Dragon","cr":10,"xp":5900,"type":"dragon","size":"Large","ac":18,"hp":178,"hpDice":"17d10+85","speed":40,"tags":["draconic","dragon","fire"]},
  {"name":"Behir","cr":11,"xp":7200,"type":"monstrosity","size":"Huge","ac":17,"hp":168,"hpDice":"16d12+64","speed":50,"tags":["monstrosity"]},
  {"name":"Djinni","cr":11,"xp":7200,"type":"elemental","size":"Large","ac":17,"hp":161,"hpDice":"14d10+84","speed":30,"tags":["elemental","elemental_construct"]},
  {"name":"Efreeti","cr":11,"xp":7200,"type":"elemental","size":"Large","ac":17,"hp":200,"hpDice":"16d10+112","speed":40,"tags":["elemental","elemental_construct","fire"]},
  {"name":"Gynosphinx","cr":11,"xp":7200,"type":"monstrosity","size":"Large","ac":17,"hp":136,"hpDice":"16d10+48","speed":40,"tags":["monstrosity"]},
  {"name":"Horned Devil","cr":11,"xp":7200,"type":"fiend","size":"Large","ac":18,"hp":178,"hpDice":"17d10+85","speed":20,"tags":["devil","fiend"]},
  {"name":"Remorhaz","cr":11,"xp":7200,"type":"monstrosity","size":"Huge","ac":17,"hp":195,"hpDice":"17d12+85","speed":30,"tags":["ice","monstrosity"]},
  {"name":"Roc","cr":11,"xp":7200,"type":"monstrosity","size":"Gargantuan","ac":15,"hp":248,"hpDice":"16d20+80","speed":20,"tags":["monstrosity"]},
  {"name":"Archmage","cr":12,"xp":8400,"type":"humanoid","size":"Medium","ac":12,"hp":99,"hpDice":"18d8+18","speed":30,"tags":["humanoid","humanoid_npc"]},
  {"name":"Erinyes","cr":12,"xp":8400,"type":"fiend","size":"Medium","ac":18,"hp":153,"hpDice":"18d8+72","speed":30,"tags":["devil","fiend"]},
  {"name":"Adult Brass Dragon","cr":13,"xp":10000,"type":"dragon","size":"Huge","ac":18,"hp":172,"hpDice":"15d12+75","speed":40,"tags":["draconic","dragon"]},
  {"name":"Adult White Dragon","cr":13,"xp":10000,"type":"dragon","size":"Huge","ac":18,"hp":200,"hpDice":"16d12+96","speed":40,"tags":["draconic","dragon","ice"]},
  {"name":"Nalfeshnee","cr":13,"xp":10000,"type":"fiend","size":"Large","ac":18,"hp":184,"hpDice":"16d10+96","speed":20,"tags":["demon","fiend"]},
  {"name":"Rakshasa","cr":13,"xp":10000,"type":"fiend","size":"Medium","ac":16,"hp":110,"hpDice":"13d8+52","speed":40,"tags":["fiend"]},
  {"name":"Storm Giant","cr":13,"xp":10000,"type":"giant","size":"Huge","ac":16,"hp":230,"hpDice":"20d12+100","speed":50,"tags":["giant","giantkin","vermin"]},
  {"name":"Vampire, Bat Form","cr":13,"xp":10000,"type":"undead","size":"Medium","ac":16,"hp":144,"hpDice":"17d8+68","speed":5,"tags":["undead","undead_theme","wild_beast"]},
  {"name":"Vampire, Mist Form","cr":13,"xp":10000,"type":"undead","size":"Medium","ac":16,"hp":144,"hpDice":"17d8+68","speed":20,"tags":["undead","undead_theme"]},
  {"name":"Vampire, Vampire Form","cr":13,"xp":10000,"type":"undead","size":"Medium","ac":16,"hp":144,"hpDice":"17d8+68","speed":30,"tags":["undead","undead_theme"]},
  {"name":"Adult Black Dragon","cr":14,"xp":11500,"type":"dragon","size":"Huge","ac":19,"hp":195,"hpDice":"17d12+85","speed":40,"tags":["draconic","dragon"]},
  {"name":"Adult Copper Dragon","cr":14,"xp":11500,"type":"dragon","size":"Huge","ac":18,"hp":184,"hpDice":"16d12+80","speed":40,"tags":["draconic","dragon"]},
  {"name":"Ice Devil","cr":14,"xp":11500,"type":"fiend","size":"Large","ac":18,"hp":180,"hpDice":"19d10+76","speed":40,"tags":["devil","fiend","ice"]},
  {"name":"Adult Bronze Dragon","cr":15,"xp":13000,"type":"dragon","size":"Huge","ac":19,"hp":212,"hpDice":"17d12+102","speed":40,"tags":["draconic","dragon"]},
  {"name":"Adult Green Dragon","cr":15,"xp":13000,"type":"dragon","size":"Huge","ac":19,"hp":207,"hpDice":"18d12+90","speed":40,"tags":["draconic","dragon"]},
  {"name":"Mummy Lord","cr":15,"xp":13000,"type":"undead","size":"Medium","ac":17,"hp":97,"hpDice":"13d8+39","speed":20,"tags":["undead","undead_theme"]},
  {"name":"Purple Worm","cr":15,"xp":13000,"type":"monstrosity","size":"Gargantuan","ac":18,"hp":247,"hpDice":"15d20+90","speed":50,"tags":["monstrosity"]},
  {"name":"Adult Blue Dragon","cr":16,"xp":15000,"type":"dragon","size":"Huge","ac":19,"hp":225,"hpDice":"18d12+108","speed":40,"tags":["draconic","dragon"]},
  {"name":"Adult Silver Dragon","cr":16,"xp":15000,"type":"dragon","size":"Huge","ac":19,"hp":243,"hpDice":"18d12+126","speed":40,"tags":["draconic","dragon"]},
  {"name":"Iron Golem","cr":16,"xp":15000,"type":"construct","size":"Large","ac":20,"hp":210,"hpDice":"20d10+100","speed":30,"tags":["construct","construct_theme","elemental_construct"]},
  {"name":"Marilith","cr":16,"xp":15000,"type":"fiend","size":"Large","ac":18,"hp":189,"hpDice":"18d10+90","speed":40,"tags":["demon","fiend"]},
  {"name":"Planetar","cr":16,"xp":15000,"type":"celestial","size":"Large","ac":19,"hp":200,"hpDice":"16d10+112","speed":40,"tags":["celestial","celestial_theme"]},
  {"name":"Adult Gold Dragon","cr":17,"xp":18000,"type":"dragon","size":"Huge","ac":19,"hp":256,"hpDice":"19d12+133","speed":40,"tags":["draconic","dragon"]},
  {"name":"Adult Red Dragon","cr":17,"xp":18000,"type":"dragon","size":"Huge","ac":19,"hp":256,"hpDice":"19d12+133","speed":40,"tags":["draconic","dragon","fire"]},
  {"name":"Androsphinx","cr":17,"xp":18000,"type":"monstrosity","size":"Large","ac":17,"hp":199,"hpDice":"19d10+95","speed":40,"tags":["monstrosity"]},
  {"name":"Dragon Turtle","cr":17,"xp":18000,"type":"dragon","size":"Gargantuan","ac":20,"hp":341,"hpDice":"22d20+110","speed":20,"tags":["draconic","dragon"]},
  {"name":"Balor","cr":19,"xp":22000,"type":"fiend","size":"Huge","ac":19,"hp":262,"hpDice":"21d12+126","speed":40,"tags":["demon","fiend"]},
  {"name":"Ancient Brass Dragon","cr":20,"xp":25000,"type":"dragon","size":"Gargantuan","ac":20,"hp":297,"hpDice":"17d20+119","speed":40,"tags":["draconic","dragon"]},
  {"name":"Ancient White Dragon","cr":20,"xp":25000,"type":"dragon","size":"Gargantuan","ac":20,"hp":333,"hpDice":"18d20+144","speed":40,"tags":["draconic","dragon","ice"]},
  {"name":"Pit Fiend","cr":20,"xp":25000,"type":"fiend","size":"Large","ac":19,"hp":300,"hpDice":"24d10+168","speed":30,"tags":["devil","fiend"]},
  {"name":"Ancient Black Dragon","cr":21,"xp":33000,"type":"dragon","size":"Gargantuan","ac":22,"hp":367,"hpDice":"21d20+147","speed":40,"tags":["draconic","dragon"]},
  {"name":"Ancient Copper Dragon","cr":21,"xp":33000,"type":"dragon","size":"Gargantuan","ac":21,"hp":350,"hpDice":"20d20+140","speed":40,"tags":["draconic","dragon"]},
  {"name":"Lich","cr":21,"xp":33000,"type":"undead","size":"Medium","ac":17,"hp":135,"hpDice":"18d8+54","speed":30,"tags":["undead","undead_theme"]},
  {"name":"Solar","cr":21,"xp":33000,"type":"celestial","size":"Large","ac":21,"hp":243,"hpDice":"18d10+144","speed":50,"tags":["celestial","celestial_theme"]},
  {"name":"Ancient Bronze Dragon","cr":22,"xp":41000,"type":"dragon","size":"Gargantuan","ac":22,"hp":444,"hpDice":"24d20+192","speed":40,"tags":["draconic","dragon"]},
  {"name":"Ancient Green Dragon","cr":22,"xp":41000,"type":"dragon","size":"Gargantuan","ac":21,"hp":385,"hpDice":"22d20+154","speed":40,"tags":["draconic","dragon"]},
  {"name":"Ancient Blue Dragon","cr":23,"xp":50000,"type":"dragon","size":"Gargantuan","ac":22,"hp":481,"hpDice":"26d20+208","speed":40,"tags":["draconic","dragon"]},
  {"name":"Ancient Silver Dragon","cr":23,"xp":50000,"type":"dragon","size":"Gargantuan","ac":22,"hp":487,"hpDice":"25d20+225","speed":40,"tags":["draconic","dragon"]},
  {"name":"Kraken","cr":23,"xp":50000,"type":"monstrosity","size":"Gargantuan","ac":18,"hp":472,"hpDice":"27d20+189","speed":20,"tags":["monstrosity"]},
  {"name":"Ancient Gold Dragon","cr":24,"xp":62000,"type":"dragon","size":"Gargantuan","ac":22,"hp":546,"hpDice":"28d20+252","speed":40,"tags":["draconic","dragon"]},
  {"name":"Ancient Red Dragon","cr":24,"xp":62000,"type":"dragon","size":"Gargantuan","ac":22,"hp":546,"hpDice":"28d20+252","speed":40,"tags":["draconic","dragon","fire"]},
  {"name":"Tarrasque","cr":30,"xp":155000,"type":"monstrosity","size":"Gargantuan","ac":25,"hp":676,"hpDice":"33d20+330","speed":40,"tags":["monstrosity"]},
];

export const MAGIC_ITEMS: Record<Rarity, MagicItem[]> = {
  common: [
    {"name":"Potion of Climbing","cat":"Potion"},
    {"name":"Potion of Healing","cat":"Potion"},
    {"name":"Spell Scroll (Cantrip)","cat":"Scroll"},
    {"name":"Spell Scroll (1st)","cat":"Scroll"},
  ],
  uncommon: [
    {"name":"Adamantine Armor","cat":"Armor"},
    {"name":"Ammunition, +1, +2, or +3","cat":"Ammunition"},
    {"name":"Ammunition, +1","cat":"Ammunition"},
    {"name":"Amulet of Proof against Detection and Location","cat":"Wondrous Items"},
    {"name":"Armor, +1, +2, or +3","cat":"Armor"},
    {"name":"Bag of Holding","cat":"Wondrous Items"},
    {"name":"Bag of Tricks","cat":"Wondrous Items"},
    {"name":"Gray Bag of Tricks","cat":"Wondrous Items"},
    {"name":"Rust Bag of Tricks","cat":"Wondrous Items"},
    {"name":"Tan Bag of Tricks","cat":"Wondrous Items"},
    {"name":"Belt of Giant Strength","cat":"Wondrous Items"},
    {"name":"Boots of Elvenkind","cat":"Wondrous Items"},
    {"name":"Boots of Striding and Springing","cat":"Wondrous Items"},
    {"name":"Boots of the Winterlands","cat":"Wondrous Items"},
    {"name":"Bracers of Archery","cat":"Wondrous Items"},
    {"name":"Brooch of Shielding","cat":"Wondrous Items"},
    {"name":"Broom of Flying","cat":"Wondrous Items"},
    {"name":"Circlet of Blasting","cat":"Wondrous Items"},
    {"name":"Cloak of Elvenkind","cat":"Wondrous Items"},
    {"name":"Cloak of Protection","cat":"Wondrous Items"},
    {"name":"Cloak of the Manta Ray","cat":"Wondrous Items"},
    {"name":"Decanter of Endless Water","cat":"Wondrous Items"},
    {"name":"Deck of Illusions","cat":"Wondrous Items"},
    {"name":"Dust of Disappearance","cat":"Wondrous Items"},
    {"name":"Dust of Dryness","cat":"Wondrous Items"},
    {"name":"Dust of Sneezing and Choking","cat":"Wondrous Items"},
    {"name":"Efficient Quiver","cat":"Wondrous Items"},
    {"name":"Elemental Gem","cat":"Wondrous Items"},
    {"name":"Air Elemental Gem","cat":"Wondrous Items"},
    {"name":"Earth Elemental Gem","cat":"Wondrous Items"},
    {"name":"Fire Elemental Gem","cat":"Wondrous Items"},
    {"name":"Water Elemental Gem","cat":"Wondrous Items"},
    {"name":"Eversmoking Bottle","cat":"Wondrous Items"},
    {"name":"Eyes of Charming","cat":"Wondrous Items"},
    {"name":"Eyes of Minute Seeing","cat":"Wondrous Items"},
    {"name":"Eyes of the Eagle","cat":"Wondrous Items"},
    {"name":"Figurine of Wondrous Power","cat":"Wondrous Items"},
    {"name":"Silver Raven Figurine of Wondrous Power","cat":"Wondrous Items"},
    {"name":"Gauntlets of Ogre Power","cat":"Wondrous Items"},
    {"name":"Gem of Brightness","cat":"Wondrous Items"},
    {"name":"Gloves of Missile Snaring","cat":"Wondrous Items"},
    {"name":"Gloves of Swimming and Climbing","cat":"Wondrous Items"},
    {"name":"Goggles of Night","cat":"Wondrous Items"},
    {"name":"Hat of Disguise","cat":"Wondrous Items"},
    {"name":"Headband of Intellect","cat":"Wondrous Items"},
    {"name":"Helm of Comprehending Languages","cat":"Wondrous Items"},
    {"name":"Helm of Telepathy","cat":"Wondrous Items"},
    {"name":"Horn of Valhalla","cat":"Wondrous Items"},
    {"name":"Immovable Rod","cat":"Rod"},
    {"name":"Ioun Stone","cat":"Wondrous Items"},
    {"name":"Javelin of Lightning","cat":"Weapon"},
    {"name":"Lantern of Revealing","cat":"Wondrous Items"},
    {"name":"Medallion of Thoughts","cat":"Wondrous Items"},
    {"name":"Mithral Armor","cat":"Armor"},
    {"name":"Necklace of Adaptation","cat":"Wondrous Items"},
    {"name":"Oil of Slipperiness","cat":"Potion"},
    {"name":"Pearl of Power","cat":"Wondrous Items"},
    {"name":"Periapt of Health","cat":"Wondrous Items"},
    {"name":"Periapt of Wound Closure","cat":"Wondrous Items"},
    {"name":"Philter of Love","cat":"Potion"},
    {"name":"Pipes of Haunting","cat":"Wondrous Items"},
    {"name":"Pipes of the Sewers","cat":"Wondrous Items"},
    {"name":"Potion of Animal Friendship","cat":"Potion"},
    {"name":"Potion of Giant Strength","cat":"Potion"},
    {"name":"Potion of Hill Giant Strength","cat":"Potion"},
    {"name":"Potion of Growth","cat":"Potion"},
    {"name":"Potion of Healing","cat":"Potion"},
    {"name":"Potion of Greater Healing","cat":"Potion"},
    {"name":"Potion of Poison","cat":"Potion"},
    {"name":"Potion of Resistance","cat":"Potion"},
    {"name":"Potion of Acid Resistance","cat":"Potion"},
    {"name":"Potion of Cold Resistance","cat":"Potion"},
    {"name":"Potion of Fire Resistance","cat":"Potion"},
    {"name":"Potion of Force Resistance","cat":"Potion"},
    {"name":"Potion of Lightning Resistance","cat":"Potion"},
    {"name":"Potion of Necrotic Resistance","cat":"Potion"},
    {"name":"Potion of Poison Resistance","cat":"Potion"},
    {"name":"Potion of Psychic Resistance","cat":"Potion"},
    {"name":"Potion of Radiant Resistance","cat":"Potion"},
    {"name":"Potion of Thunder Resistance","cat":"Potion"},
    {"name":"Potion of Water Breathing","cat":"Potion"},
    {"name":"Restorative Ointment","cat":"Wondrous Items"},
    {"name":"Ring of Jumping","cat":"Ring"},
    {"name":"Ring of Mind Shielding","cat":"Ring"},
    {"name":"Ring of Swimming","cat":"Ring"},
    {"name":"Ring of Warmth","cat":"Ring"},
    {"name":"Ring of Water Walking","cat":"Ring"},
    {"name":"Robe of Useful Items","cat":"Wondrous Items"},
    {"name":"Rope of Climbing","cat":"Wondrous Items"},
    {"name":"Slippers of Spider Climbing","cat":"Wondrous Items"},
    {"name":"Spell Scroll","cat":"Scroll"},
    {"name":"Spell Scroll (2nd)","cat":"Scroll"},
    {"name":"Spell Scroll (3rd)","cat":"Scroll"},
    {"name":"Stone of Good Luck (Luckstone)","cat":"Wondrous Items"},
    {"name":"Trident of Fish Command","cat":"Weapon"},
    {"name":"Wand of Magic Detection","cat":"Wand"},
    {"name":"Wand of Magic Missiles","cat":"Wand"},
    {"name":"Wand of Secrets","cat":"Wand"},
    {"name":"Wand of the War Mage, +1, +2, or +3","cat":"Wand"},
    {"name":"Wand of the War Mage, +1","cat":"Wand"},
    {"name":"Wand of Web","cat":"Wand"},
    {"name":"Weapon, +1, +2, or +3","cat":"Weapon"},
    {"name":"Weapon, +1","cat":"Weapon"},
    {"name":"Wind Fan","cat":"Wondrous Items"},
    {"name":"Winged Boots","cat":"Wondrous Items"},
  ],
  rare: [
    {"name":"Ammunition, +2","cat":"Ammunition"},
    {"name":"Amulet of Health","cat":"Wondrous Items"},
    {"name":"Armor, +1","cat":"Armor"},
    {"name":"Armor of Resistance","cat":"Armor"},
    {"name":"Armor of Vulnerability","cat":"Armor"},
    {"name":"Arrow-Catching Shield","cat":"Armor"},
    {"name":"Bag of Beans","cat":"Wondrous Items"},
    {"name":"Bead of Force","cat":"Wondrous Items"},
    {"name":"Belt of Dwarvenkind","cat":"Wondrous Items"},
    {"name":"Belt of Hill Giant Strength","cat":"Wondrous Items"},
    {"name":"Berserker Axe","cat":"Weapon"},
    {"name":"Boots of Levitation","cat":"Wondrous Items"},
    {"name":"Boots of Speed","cat":"Wondrous Items"},
    {"name":"Bowl of Commanding Water Elementals","cat":"Wondrous Items"},
    {"name":"Bracers of Defense","cat":"Wondrous Items"},
    {"name":"Brazier of Commanding Fire Elementals","cat":"Wondrous Items"},
    {"name":"Cape of the Mountebank","cat":"Wondrous Items"},
    {"name":"Censer of Controlling Air Elementals","cat":"Wondrous Items"},
    {"name":"Chime of Opening","cat":"Wondrous Items"},
    {"name":"Cloak of Displacement","cat":"Wondrous Items"},
    {"name":"Cloak of the Bat","cat":"Wondrous Items"},
    {"name":"Cube of Force","cat":"Wondrous Items"},
    {"name":"Dagger of Venom","cat":"Weapon"},
    {"name":"Dimensional Shackles","cat":"Wondrous Items"},
    {"name":"Dragon Slayer","cat":"Weapon"},
    {"name":"Elven Chain","cat":"Armor"},
    {"name":"Feather Token","cat":"Wondrous Items"},
    {"name":"Anchor Feather Token","cat":"Wondrous Items"},
    {"name":"Bird Feather Token","cat":"Wondrous Items"},
    {"name":"Fan Feather Token","cat":"Wondrous Items"},
    {"name":"Swan Boat Feather Token","cat":"Wondrous Items"},
    {"name":"Tree Feather Token","cat":"Wondrous Items"},
    {"name":"Whip Feather Token","cat":"Wondrous Items"},
    {"name":"Bronze Griffon Figurine of Wondrous Power","cat":"Wondrous Items"},
    {"name":"Ebony Fly Figurine of Wondrous Power","cat":"Wondrous Items"},
    {"name":"Golden Lions Figurine of Wondrous Power","cat":"Wondrous Items"},
    {"name":"Ivory Goats Figurine of Wondrous Power","cat":"Wondrous Items"},
    {"name":"Marble Elephant Figurine of Wondrous Power","cat":"Wondrous Items"},
    {"name":"Onyx Dog Figurine of Wondrous Power","cat":"Wondrous Items"},
    {"name":"Serpentine Owl Figurine of Wondrous Power","cat":"Wondrous Items"},
    {"name":"Flame Tongue","cat":"Weapon"},
    {"name":"Folding Boat","cat":"Wondrous Items"},
    {"name":"Gem of Seeing","cat":"Wondrous Items"},
    {"name":"Giant Slayer","cat":"Weapon"},
    {"name":"Glamoured Studded Leather Armor","cat":"Armor"},
    {"name":"Handy Haversack","cat":"Wondrous Items"},
    {"name":"Helm of Teleportation","cat":"Wondrous Items"},
    {"name":"Horn of Blasting","cat":"Wondrous Items"},
    {"name":"Silver Horn of Valhalla","cat":"Wondrous Items"},
    {"name":"Brass Horn of Valhalla","cat":"Wondrous Items"},
    {"name":"Horseshoes of Speed","cat":"Wondrous Items"},
    {"name":"Instant Fortress","cat":"Wondrous Items"},
    {"name":"Ioun Stone of Awareness","cat":"Wondrous Items"},
    {"name":"Ioun Stone of Protection","cat":"Wondrous Items"},
    {"name":"Ioun Stone of Reserve","cat":"Wondrous Items"},
    {"name":"Ioun Stone of Sustenance","cat":"Wondrous Items"},
    {"name":"Iron Bands of Binding","cat":"Wondrous Items"},
    {"name":"Mace of Disruption","cat":"Weapon"},
    {"name":"Mace of Smiting","cat":"Weapon"},
    {"name":"Mace of Terror","cat":"Weapon"},
    {"name":"Mantle of Spell Resistance","cat":"Wondrous Items"},
    {"name":"Necklace of Fireballs","cat":"Wondrous Items"},
    {"name":"Necklace of Prayer Beads","cat":"Wondrous Items"},
    {"name":"Oil of Etherealness","cat":"Potion"},
    {"name":"Periapt of Proof against Poison","cat":"Wondrous Items"},
    {"name":"Portable Hole","cat":"Wondrous Items"},
    {"name":"Potion of Clairvoyance","cat":"Potion"},
    {"name":"Potion of Diminution","cat":"Potion"},
    {"name":"Potion of Gaseous Form","cat":"Potion"},
    {"name":"Potion of Frost Giant Strength","cat":"Potion"},
    {"name":"Potion of Stone Giant Strength","cat":"Potion"},
    {"name":"Potion of Fire Giant Strength","cat":"Potion"},
    {"name":"Potion of Superior Healing","cat":"Potion"},
    {"name":"Potion of Heroism","cat":"Potion"},
    {"name":"Potion of Mind Reading","cat":"Potion"},
    {"name":"Ring of Animal Influence","cat":"Ring"},
    {"name":"Ring of Evasion","cat":"Ring"},
    {"name":"Ring of Feather Falling","cat":"Ring"},
    {"name":"Ring of Free Action","cat":"Ring"},
    {"name":"Ring of Protection","cat":"Ring"},
    {"name":"Ring of Resistance","cat":"Ring"},
    {"name":"Ring of Acid Resistance","cat":"Ring"},
    {"name":"Ring of Cold Resistance","cat":"Ring"},
    {"name":"Ring of Fire Resistance","cat":"Ring"},
    {"name":"Ring of Force Resistance","cat":"Ring"},
    {"name":"Ring of Lightning Resistance","cat":"Ring"},
    {"name":"Ring of Necrotic Resistance","cat":"Ring"},
    {"name":"Ring of Poison Resistance","cat":"Ring"},
    {"name":"Ring of Psychic Resistance","cat":"Ring"},
    {"name":"Ring of Radiant Resistance","cat":"Ring"},
    {"name":"Ring of Thunder Resistance","cat":"Ring"},
    {"name":"Ring of Spell Storing","cat":"Ring"},
    {"name":"Ring of the Ram","cat":"Ring"},
    {"name":"Ring of X-ray Vision","cat":"Ring"},
    {"name":"Robe of Eyes","cat":"Wondrous Items"},
    {"name":"Rod of Rulership","cat":"Rod"},
    {"name":"Rope of Entanglement","cat":"Wondrous Items"},
    {"name":"Shield of Missile Attraction","cat":"Armor"},
    {"name":"Spell Scroll (4th)","cat":"Scroll"},
    {"name":"Spell Scroll (5th)","cat":"Scroll"},
    {"name":"Staff of Charming","cat":"Staff"},
    {"name":"Staff of Healing","cat":"Staff"},
    {"name":"Staff of the Woodlands","cat":"Staff"},
    {"name":"Staff of Withering","cat":"Staff"},
    {"name":"Stone of Controlling Earth Elementals","cat":"Wondrous Items"},
    {"name":"Sun Blade","cat":"Weapon"},
    {"name":"Sword of Life Stealing","cat":"Weapon"},
    {"name":"Sword of Wounding","cat":"Weapon"},
    {"name":"Vicious Weapon","cat":"Weapon"},
    {"name":"Wand of Binding","cat":"Wand"},
    {"name":"Wand of Enemy Detection","cat":"Wand"},
    {"name":"Wand of Fear","cat":"Wand"},
    {"name":"Wand of Fireballs","cat":"Wand"},
    {"name":"Wand of Lightning Bolts","cat":"Wand"},
    {"name":"Wand of Paralysis","cat":"Wand"},
    {"name":"Wand of the War Mage, +2","cat":"Wand"},
    {"name":"Wand of Wonder","cat":"Wand"},
    {"name":"Weapon, +2","cat":"Weapon"},
    {"name":"Wings of Flying","cat":"Wondrous Items"},
  ],
  veryRare: [
    {"name":"Ammunition, +3","cat":"Ammunition"},
    {"name":"Amulet of the Planes","cat":"Wondrous Items"},
    {"name":"Animated Shield","cat":"Armor"},
    {"name":"Armor, +2","cat":"Armor"},
    {"name":"Arrow of Slaying","cat":"Ammunition"},
    {"name":"Bag of Devouring","cat":"Wondrous Items"},
    {"name":"Belt of Stone Giant Strength","cat":"Wondrous Items"},
    {"name":"Belt of Frost Giant Strength","cat":"Wondrous Items"},
    {"name":"Belt of Fire Giant Strength","cat":"Wondrous Items"},
    {"name":"Candle of Invocation","cat":"Wondrous Items"},
    {"name":"Carpet of Flying","cat":"Wondrous Items"},
    {"name":"Carpet of Flying (3 ft. × 5 ft.)","cat":"Wondrous Items"},
    {"name":"Carpet of Flying (4 ft. × 6 ft.)","cat":"Wondrous Items"},
    {"name":"Carpet of Flying (5 ft. × 7 ft.)","cat":"Wondrous Items"},
    {"name":"Carpet of Flying (6 ft. × 9 ft.)","cat":"Wondrous Items"},
    {"name":"Cloak of Arachnida","cat":"Wondrous Items"},
    {"name":"Crystal Ball","cat":"Wondrous Items"},
    {"name":"Dancing Sword","cat":"Weapon"},
    {"name":"Demon Armor","cat":"Armor"},
    {"name":"Dragon Scale Mail","cat":"Armor"},
    {"name":"Black Dragon Scale Mail","cat":"Armor"},
    {"name":"Blue Dragon Scale Mail","cat":"Armor"},
    {"name":"Brass Dragon Scale Mail","cat":"Armor"},
    {"name":"Bronze Dragon Scale Mail","cat":"Armor"},
    {"name":"Copper Dragon Scale Mail","cat":"Armor"},
    {"name":"Gold Dragon Scale Mail","cat":"Armor"},
    {"name":"Green Dragon Scale Mail","cat":"Armor"},
    {"name":"Red Dragon Scale Mail","cat":"Armor"},
    {"name":"Silver Dragon Scale Mail","cat":"Armor"},
    {"name":"White Dragon Scale Mail","cat":"Armor"},
    {"name":"Dwarven Plate","cat":"Armor"},
    {"name":"Dwarven Thrower","cat":"Weapon"},
    {"name":"Efreeti Bottle","cat":"Wondrous Items"},
    {"name":"Obsidian Steed Figurine of Wondrous Power","cat":"Wondrous Items"},
    {"name":"Frost Brand","cat":"Weapon"},
    {"name":"Helm of Brilliance","cat":"Wondrous Items"},
    {"name":"Bronze Horn of Valhalla","cat":"Wondrous Items"},
    {"name":"Horseshoes of a Zephyr","cat":"Wondrous Items"},
    {"name":"Ioun Stone of Absorption","cat":"Wondrous Items"},
    {"name":"Ioun Stone of Agility","cat":"Wondrous Items"},
    {"name":"Ioun Stone of Fortitude","cat":"Wondrous Items"},
    {"name":"Ioun Stone of Insight","cat":"Wondrous Items"},
    {"name":"Ioun Stone of Intellect","cat":"Wondrous Items"},
    {"name":"Ioun Stone of Leadership","cat":"Wondrous Items"},
    {"name":"Ioun Stone of Strength","cat":"Wondrous Items"},
    {"name":"Manual of Bodily Health","cat":"Wondrous Items"},
    {"name":"Manual of Gainful Exercise","cat":"Wondrous Items"},
    {"name":"Manual of Golems","cat":"Wondrous Items"},
    {"name":"Manual of Clay Golems","cat":"Wondrous Items"},
    {"name":"Manual of Flesh Golems","cat":"Wondrous Items"},
    {"name":"Manual of Iron Golems","cat":"Wondrous Items"},
    {"name":"Manual of Stone Golems","cat":"Wondrous Items"},
    {"name":"Manual of Quickness of Action","cat":"Wondrous Items"},
    {"name":"Marvelous Pigments","cat":"Wondrous Items"},
    {"name":"Mirror of Life Trapping","cat":"Wondrous Items"},
    {"name":"Nine Lives Stealer","cat":"Weapon"},
    {"name":"Oathbow","cat":"Weapon"},
    {"name":"Oil of Sharpness","cat":"Potion"},
    {"name":"Potion of Flying","cat":"Potion"},
    {"name":"Potion of Cloud Giant Strength","cat":"Potion"},
    {"name":"Potion of Supreme Healing","cat":"Potion"},
    {"name":"Potion of Invisibility","cat":"Potion"},
    {"name":"Potion of Speed","cat":"Potion"},
    {"name":"Ring of Regeneration","cat":"Ring"},
    {"name":"Ring of Shooting Stars","cat":"Ring"},
    {"name":"Ring of Telekinesis","cat":"Ring"},
    {"name":"Robe of Scintillating Colors","cat":"Wondrous Items"},
    {"name":"Robe of Stars","cat":"Wondrous Items"},
    {"name":"Rod of Absorption","cat":"Rod"},
    {"name":"Rod of Alertness","cat":"Rod"},
    {"name":"Rod of Security","cat":"Rod"},
    {"name":"Scimitar of Speed","cat":"Weapon"},
    {"name":"Spell Scroll (6th)","cat":"Scroll"},
    {"name":"Spell Scroll (7th)","cat":"Scroll"},
    {"name":"Spell Scroll (8th)","cat":"Scroll"},
    {"name":"Spellguard Shield","cat":"Armor"},
    {"name":"Staff of Fire","cat":"Staff"},
    {"name":"Staff of Frost","cat":"Staff"},
    {"name":"Staff of Power","cat":"Staff"},
    {"name":"Staff of Striking","cat":"Staff"},
    {"name":"Staff of Swarming Insects","cat":"Staff"},
    {"name":"Staff of the Python","cat":"Staff"},
    {"name":"Staff of Thunder and Lightning","cat":"Staff"},
    {"name":"Sword of Sharpness","cat":"Weapon"},
    {"name":"Tome of Clear Thought","cat":"Wondrous Items"},
    {"name":"Tome of Leadership and Influence","cat":"Wondrous Items"},
    {"name":"Tome of Understanding","cat":"Wondrous Items"},
    {"name":"Wand of Polymorph","cat":"Wand"},
    {"name":"Wand of the War Mage, +3","cat":"Wand"},
    {"name":"Weapon, +3","cat":"Weapon"},
  ],
  legendary: [
    {"name":"Apparatus of the Crab","cat":"Wondrous Items"},
    {"name":"Armor, +3","cat":"Armor"},
    {"name":"Armor of Invulnerability","cat":"Armor"},
    {"name":"Belt of Cloud Giant Strength","cat":"Wondrous Items"},
    {"name":"Belt of Storm Giant Strength","cat":"Wondrous Items"},
    {"name":"Crystal Ball of Mind Reading","cat":"Wondrous Items"},
    {"name":"Crystal Ball of Telepathy","cat":"Wondrous Items"},
    {"name":"Crystal Ball of True Seeing","cat":"Wondrous Items"},
    {"name":"Cubic Gate","cat":"Wondrous Items"},
    {"name":"Deck of Many Things","cat":"Wondrous Items"},
    {"name":"Defender","cat":"Weapon"},
    {"name":"Hammer of Thunderbolts","cat":"Weapon"},
    {"name":"Holy Avenger","cat":"Weapon"},
    {"name":"Iron Horn of Valhalla","cat":"Wondrous Items"},
    {"name":"Ioun Stone of Greater Absorption","cat":"Wondrous Items"},
    {"name":"Ioun Stone of Mastery","cat":"Wondrous Items"},
    {"name":"Ioun Stone of Regeneration","cat":"Wondrous Items"},
    {"name":"Iron Flask","cat":"Wondrous Items"},
    {"name":"Luck Blade","cat":"Weapon"},
    {"name":"Plate Armor of Etherealness","cat":"Armor"},
    {"name":"Potion of Storm Giant Strength","cat":"Potion"},
    {"name":"Ring of Djinni Summoning","cat":"Ring"},
    {"name":"Ring of Elemental Command","cat":"Ring"},
    {"name":"Ring of Air Elemental Command","cat":"Ring"},
    {"name":"Ring of Earth Elemental Command","cat":"Ring"},
    {"name":"Ring of Fire Elemental Command","cat":"Ring"},
    {"name":"Ring of Water Elemental Command","cat":"Ring"},
    {"name":"Ring of Invisibility","cat":"Ring"},
    {"name":"Ring of Spell Turning","cat":"Ring"},
    {"name":"Ring of Three Wishes","cat":"Ring"},
    {"name":"Robe of the Archmagi","cat":"Wondrous Items"},
    {"name":"Rod of Lordly Might","cat":"Rod"},
    {"name":"Scarab of Protection","cat":"Wondrous Items"},
    {"name":"Sovereign Glue","cat":"Wondrous Items"},
    {"name":"Spell Scroll (9th)","cat":"Scroll"},
    {"name":"Sphere of Annihilation","cat":"Wondrous Items"},
    {"name":"Staff of the Magi","cat":"Staff"},
    {"name":"Talisman of Pure Good","cat":"Wondrous Items"},
    {"name":"Talisman of the Sphere","cat":"Wondrous Items"},
    {"name":"Talisman of Ultimate Evil","cat":"Wondrous Items"},
    {"name":"Universal Solvent","cat":"Wondrous Items"},
    {"name":"Vorpal Sword","cat":"Weapon"},
    {"name":"Well of Many Worlds","cat":"Wondrous Items"},
  ],
};
